# This is a basic workflow to help you get started with Actions

name: build-to-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Install .NET 7.0 SDK
      - name: Setup .NET 7 preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
          
      # Instal wasm-tools
      - name: Setup wasm-tools
        run: dotnet workload restore ./Alcedosoft.Blazor.Sqlite.Sample/Alcedosoft.Blazor.Sqlite.Sample.csproj

      - name: Publish app
        run: dotnet publish -c Release -o build ./Alcedosoft.Blazor.Sqlite.Sample/Alcedosoft.Blazor.Sqlite.Sample.csproj
  
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: build/wwwroot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
